### ISSUE TITLE
全橙通关！

### ISSUE THREAD

**Issue by YuYanzy** [Renovamen/midgard#11]
![image](https://user-images.githubusercontent.com/25244419/120792051-89416600-c567-11eb-99a9-eb20cfbcfe06.png)

**Comment by Renovamen** [comment]
啥啥啥您还真全橙了？啊真的太强了太强了 😂

**Comment by Renovamen** [comment]
作弊码技巧：点头像，在输入框里输入 `xiaohanzouissocool`，你就啥都有了（狗头

**Comment by YuYanzy** [comment]
> 作弊码技巧：点头像，在输入框里输入 `xiaohanzouissocool`，你就啥都有了（狗头

就是这么通关的。
这游戏全橙既肝又欧才行，上次吃饭前肝了一个多小时愣是差一个。
在看 playgroud-macOS 项目的源码的时候大为触动，然后突然想到看看这个源码，虽然不会 Vue，但是居然有意外收获，发现了作弊码……
之后学了 Vue 再来学习~

**Comment by Renovamen** [comment]
啊仔细看了看的确是用了作弊码的效果

加油嗷朋友

**Comment by YuYanzy** [comment]
共勉~
